### ISSUE TITLE
README - reminder  voor dataset info

### ISSUE THREAD

**Issue by randy554** [basv1996/FunctionalProgramming#2]
Je README.md ziet er al heel nice uit 💪 . Wellicht was je dit al van plan maar je zou onder het kopje data nog wat kunnen vertellen over de dataset/API die je gebruik hebt voor dit project. Een screenshot (a picture is worth a thousand words) met een korte omschrijving geeft een aardig beeld over de data die gebruikt is.

**Comment by basv1996** [comment]
Thanks for the tip my man, implemented it into the ReadMe
