### ISSUE TITLE
WIKI - Afbeeldingen

### ISSUE THREAD

**Issue by randy554** [basv1996/FunctionalProgramming#5]
Je wiki ziet er nice uit 😎 ! Je hebt je logboek goed bijgehouden, je omschrijft je process en beweegredenen. Ik heb er weinig op aan te merken 🙌 . Ik zie dat je af en toe gebruik maakt van screenshots om code weer te geven, wellicht is [deze tool](https://carbon.now.sh/) hier beter geschikt voor.

**Comment by basv1996** [comment]
wow that is looking sick, great tip!!
