### ISSUE TITLE
Dubbele data.js bestand?

### ISSUE THREAD

**Issue by randy554** [basv1996/FunctionalProgramming#6]
Heb je een bestand dubbel in je project zitten of zie ik het verkeerd?

https://github.com/basv1996/FunctionalProgramming/blob/8f6bf76f151b7f97d53abb291c643eae7b226c46/data/data.json#L3

https://github.com/basv1996/FunctionalProgramming/blob/8f6bf76f151b7f97d53abb291c643eae7b226c46/scripts/data.js#L3

**Comment by basv1996** [comment]
het zijn 2 verschillende bestanden, de 1 i een JS en de ander een JSON bestand
